module.exports = {
  FB_PAGE_TOKEN:
"EAADZB6mW8cu0BAM9l1X3lUvCj7uHFOa4ZAI9ZA0QJy90KJi0zhz2ZBNhv1OxMmY3AjZCJJ0IqSwKW4fbNLuP8aN84rt70JuZBfKh0x8eIkwAjC43vdKjHYGIBBcOVGaM2ZCQzIgGOvLukJxSFMV6qA0ihMG7c3HBY2kDvBmURDvZBAZDZD",
  FB_VERIFY_TOKEN: "facebookbot",
  FB_APP_SECRET: "51a4eb40d5d7cb21cfefc3f5d2a0fab4",
  SERVER_URL: "https://ebf8dc7e.ngrok.io/",
  GOOGLE_PROJECT_ID: "fir-a3c6b",
  DF_LANGUAGE_CODE: "en-us",
  "GOOGLE_CLIENT_EMAIL": "dialogflow-dkaklq@fir-a3c6b.iam.gserviceaccount.com",
  "GOOGLE_PRIVATE_KEY": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC2s2omF2/xf5gt\n0O+bcwbgavuqsUb8MnGxdn7WMif7ITym3NVnPfdguFl2zldCYyq2CLbI8DVGR2yu\nLr4J8qg68DMzSDBMxkiuK444F9ON7g4L05gTMEVoiCMqfFMrY4H225sA3NMenLKv\njC807AOUXWI9G1xvN8jCveGOxRjQXrwm9EYXHME8KagjTfF1ZicSVGFz9AZtH1JP\nLYPFNLaO0iz9nK2fCVFC68IQrXavJZf1okrhtOt5JbOg25M5jm8qCrDUrMBn9vWZ\nwE06DaAPB2yjYT42TUbUhsgXQQOazrJVUlPPwqnxEA8yh1S4l19RdPFTaSOwFoOc\n0RG81kobAgMBAAECggEAEEJyYXZ3g3YYDIfKMzru8z0CLcQ+LYatwJ3rltN65Gom\nVDFWGqyUnfp6F80wTdu2euHWppZeH2WO4geN6SO73hbvb5Junf6NjFaa/xn7vWdg\nv6Oypo6GttFa09ahrjxaXiZYKqD8dv56Fo5yyxJwFR2kdwy+0rUTvGUatFKNLUoC\ngxCocVKSNO5pvVRfMPGJ/nTs2AxOpBs6tgXFmCSoqN5vX+6JgCOEtVNxSNHf+nW7\nzE7+mYn9bM7PWlxSQWDvk7ATJMsvJYgwilyMio7B0adiN3r9WQCwo3GVg38YFpR9\n1oWPx50dii2gFSjgnz4TT+tEV1OUh1Rbl438v2F2KQKBgQDlyYmM5GhF7EZPlu75\nSTAaIlnXIX/UeI8Ie27v9LJzhfQE4Z2wwLcY6OZ5JVzVEvxq4zP1CmXxAgfKdIdw\nDjiHcWGPSf4tXtRwBPI3/Wd8D/2X7b2jJMZa9yDs92yFtpKCUgAtI9qHAmQJ/by1\nqNxQX0JgQGSc7klqEp4bDkRjowKBgQDLitDQ21DB///You0zU0PQPCghglr4jGRF\n0mgPqNHCRrq5o5qs9JLV+X7cXODkIrPRy/i1dVDSy7rzBPjLBoB13C9AGKh52qkR\nyr6MqY3JNacweMB45h2//Sp40x/DRvHWj36Od+Y+C2+XcRnP4tIOLZ+xVK78vh6F\n2N8588GnKQKBgQC24nBXcnKLNEHBlp8cSOO/6RcX4dGbiVhNp+/jix18VGCige6/\nfqI7cSH9yX7ZFwNPDwWLQXthFfydZaFlzeuv4M2E/Z8O/SqW/VjKtyRl2VQ8VztX\nXS2BuK676zC0O1rf3ePGCYMjcQOt8AUBkCPI1AhAEwAA5qYHhknPvssvgQKBgQCC\nJmdTxYkkI7/DFJs8AHgSRQUcODBXUd4kT2A+8yH9aiCn55dWFKV3sSuPWMxs1EvL\nUPPdhACEacVG89zqZWPq+To1cA76q/kD6XJim2CQUoBvnCbmp65KP2XTEJz0zv6A\nxgyUqNJOxh065xUsOss6Sa4dRBsIfcEisQQ8GEOx0QKBgCCX+OdN5TbUWtvAXGlg\nkS9AqK7kTkifIE6Id9Chczp2ynBfhGllLcIZz8TIXY8h8ro81blmvAhq+7D7H1E5\nfBa9AJQFsLecXI3zlpnND7gFPF8IeQrbof4lsMJYL6UzifYJkNaJU0YeLhAOtr0m\n9epK+mF8yqqSSI4woYkZETRh\n-----END PRIVATE KEY-----\n",

   cars : ["AC",
"Acura",
"Alfa Romeo",
"AM General",
"American Motors (AMC)",
"Amphicar",
"Aston Martin",
"Audi",
"Austin",
"Austin-Healey",
"Bentley",
"BMW",
"Bricklin",
"Bugatti",
"Buick",
"Cadillac",
"Caterham",
"Chevrolet",
"Chrysler",
"Daewoo",
"Daihatsu",
"Datsun",
"De Soto",
"DeLorean",
"Diamond T",
"DKW",
"Dodge",
"Dodge or Ram",
"Eagle",
"Factory Five Racing",
"Ferrari",
"Fiat",
"Fisker",
"Ford",
"Gazelle",
"Genesis",
"Geo",
"GMC",
"Hino",
"Honda",
"Hudson",
"Hummer",
"Hupmobile",
"Hyundai",
"Infiniti",
"International",
"Isuzu",
"Jaguar",
"Jeep",
"Kaiser",
"Karma",
"Kia",
"Lada",
"Lamborghini",
"Land Rover",
"Lexus",
"Lincoln",
"Lotus",
"Maserati",
"Maybach",
"Mazda",
"McLaren",
"Mercedes-AMG",
"Mercedes-Benz",
"Mercury",
"MG",
"MINI",
"Mitsubishi",
"Morgan",
"Morris",
"MV-1",
"Nash",
"Nissan",
"Oldsmobile",
"Packard",
"Plymouth",
"Pontiac",
"Porsche",
"Radical",
"Ram",
"Renault",
"Rolls-Royce",
"Rover",
"Saab",
"Saleen",
"Saturn",
"Scion",
"Shelby",
"smart",
"Spyker",
"Sterling",
"Studebaker",
"Subaru",
"Sunbeam",
"Suzuki",
"Tesla",
"Toyota",
"Triumph",
"TVR",
"Vauxhall",
"Volkswagen",
"Volvo",
"Willys",
]
  };
